[build]
  publish = "."

[[redirects]]
  from = "/"
  to = "/final.html"
  status = 200
  force = true

[[redirects]]
  from = "/index.html"
  to = "/final.html"
  status = 200
  force = true

[[redirects]]
  from = "/app.html"
  to = "/final.html"
  status = 200
  force = true

[[redirects]]
  from = "/main.html"
  to = "/final.html"
  status = 200
  force = true

[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Cache-Control = "no-cache, no-store, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"

[[headers]]
  for = "/manifest.json"
  [headers.values]
    Content-Type = "application/manifest+json"
    Cache-Control = "no-cache"

[[headers]]
  for = "/service-worker.js"
  [headers.values]
    Content-Type = "application/javascript"
    Cache-Control = "no-cache"

[[headers]]
  for = "/final.html"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"
